import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/index.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p className={styles.title}>LOL KRYPTONITE</p>
        <form className={styles.searchForm}>
          <div>
            <select className={styles.server}>
              <option selected value="NA">NA</option>
              <option value="EUW">EUW</option>
              <option value="EUNE">EUNE</option>
              <option value="KR">KR</option>
            </select>
          </div>
          <div>
            <input type="text" className={styles.searchSummoner} placeholder="Summoner Name" value="" />
          </div>
          <button type="submit" className = {styles.searchButton}>Search</button>
        </form>
        <p className={styles.description}>
          Discover your League of Legends kryptonite champion(s) based <br></br>
          on your match history and winrates vs each champion.
        </p>
      </main>
    </>
  )
}
